// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
// https://fernandorojo.co
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";
import { Ref, forwardRef } from "react";

const Minimize = (props: SvgProps, ref: Ref<SVGSVGElement>) => <Svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><Path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.25 19.25V16.75C9.25 15.6454 8.35457 14.75 7.25 14.75H4.75" /><Path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M14.75 19.25V16.75C14.75 15.6454 15.6454 14.75 16.75 14.75H19.25" /><Path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M14.75 4.75V7.25C14.75 8.35457 15.6454 9.25 16.75 9.25H19.25" /><Path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.25 4.75V7.25C9.25 8.35457 8.35457 9.25 7.25 9.25H4.75" /></Svg>;

const ForwardRef = forwardRef(Minimize);
export default ForwardRef;