// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
// https://fernandorojo.co
import * as React from "react";
import Svg, { SvgProps, Path, Circle } from "react-native-svg";
import { Ref, forwardRef } from "react";

const ShoppingCart = (props: SvgProps, ref: Ref<SVGSVGElement>) => <Svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><Path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M7.75 7.75H19.25L17.6128 14.7081C17.4002 15.6115 16.5941 16.25 15.666 16.25H11.5395C10.632 16.25 9.83827 15.639 9.60606 14.7618L7.75 7.75ZM7.75 7.75L7 4.75H4.75" /><Circle cx={10} cy={19} r={1} fill="currentColor" /><Circle cx={17} cy={19} r={1} fill="currentColor" /></Svg>;

const ForwardRef = forwardRef(ShoppingCart);
export default ForwardRef;