// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
// https://fernandorojo.co
import * as React from "react";
import Svg, { SvgProps, Rect } from "react-native-svg";
import { Ref, forwardRef } from "react";

const Stop = (props: SvgProps, ref: Ref<SVGSVGElement>) => <Svg width={24} height={24} fill="none" viewBox="0 0 24 24" ref={ref} {...props}><Rect width={12.5} height={12.5} x={5.75} y={5.75} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} rx={1} /></Svg>;

const ForwardRef = forwardRef(Stop);
export default ForwardRef;